# =============================================================================
# Codecov Configuration
# =============================================================================
# Coverage reporting settings
# Docs: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 50%
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "notebooks/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
